### ISSUE TITLE
Mpox 2024 CAR suspected/discarded cases

### ISSUE THREAD

**Issue by jackie-powers** [globaldothealth/outbreak-data#49]
Just looked at the CAR cases and this is what I found:

- On 8/25, ACDC says 247 suspected cases are discarded (we had 223 but those all become discarded on our tracker).
- Only confirmed cases are reported on 8/25 and 8/31.
- On 9/8, there are 20 new cases. They don’t explicitly use the word “suspected” and just say they are not lab-confirmed. It could be that these are cases that have not yet been tested (247/278 tested that week). Cumulatively, there are 230 non lab-confirmed cases. We discarded 223 cases, so if they didn’t zero their numbers we would expect 243 total suspected (20+223). It’s unclear whether the cumulative includes these discarded cases (230 in report vs. 243 if they included discarded cases)
- On 9/23, there are 22 new cases. They again don’t explicitly say “suspected.” The confusing part is that out of the cumulative 307 cases, all 307 were tested. So I’m not sure how there would be suspected cases since I would assume that they know these cases are negative. (Maybe the results hadn’t come back at that point?)

My initial conclusion is that it seems like they are trying to test all the cases and it seems like these “new” cases are awaiting testing which may be why the suspected cases keeps fluctuating. However, they still include these new cases even when there is 100% testing rate. Please let me know how you interpret this.

I’m also unsure of whether the cumulative totals include the previous discarded cases. The math isn’t adding up so it’s hard to tell.

**Comment by aimeehan1** [comment]
Question we need to decide as a group: Do the cumulative totals include the previous discarded cases????
I think the cumulative counts include discarded cases. 
So, we will need to 
1) flip 32 suspected cases to 'Discarded' to equal 255. Then,
2) omit_error the remainder of the suspected cases since they continue to report 100% testing rate. our totals will match the 9/23 ACDC report 307 cases, of which 52 were lab-confirmed. Then 
3) add a note to Github and consider adding a Footnote to the briefing report that explains the calculation.

**Comment by JacqSauer** [comment]
@aimeehan1 @jackie-powers @julianasopko CAR has been updated, moving on to addressing Rwanda and other countries that may have this issue. Once complete, I will resolve these tickets and open one for the footnote in the briefing report
