### ISSUE TITLE
Mpox 2024- Do WHO case counts include suspected and discarded?

### ISSUE THREAD

**Issue by JacqSauer** [globaldothealth/outbreak-data#55]
The who is reporting suspected and confirmed cases only, and it is hard to determine if these suspected case counts also include discarded cases. We are running into an issue where we are adding too many cases based on this.

For example, the WHO reports 14 confirmed cases and 230 suspected cases in Kenya. In our line list, we have reported 14 confirmed mpox cases, 230 suspected cases, and 225 discarded cases. In ACDC reports for Kenya, the report mentions that all cases were tested (100%) testing rate, which is why we have reported discarded cases for Kenya. As a team, we should consider if we want to keep adding in cases as discarded for countries with a 100% testing rate, or if we want to follow the WHO dashboard and only report 'suspected' and 'confirmed' cases.

Once we have made a decision, we will update our case counts (example: we need to omit either the 225 discarded cases and only keep the 230 suspected cases following WHO format, or we omit the 230 suspected cases and keep the 225 discarded cases following ACDC format for Kenya).

Here is what the WHO dashboard website says about negative/discarded cases: " In some countries, suspected cases that undergo testing are not removed from the count, regardless of whether the test result is positive (confirmed case) or negative (discarded case). Moreover, not all countries have robust surveillance systems for mpox, meaning reported case counts are likely underestimate the extent of community transmission."

**Comment by JacqSauer** [comment]
this is also present in Liberia:
WHO reports 19 confirmed cases and 225 suspected cases
ACDC reports 19 confirmed cases and 254 total cases, of which 185 presumably tested negative and 19 tested positive.
Our line list reports 19 confirmed cases in Liberia, 178 discarded cases, and 225 suspected cases.
Our options include: 
1. only report numbers according to WHO (19 confirmed, 225 suspected) and omit all the discarded (178) cases
2. report the numbers from ACDC (19 confirmed, 185 discarded, and 50 suspected (254 total cases)), which means we would need to omit 175 suspected cases

@aimeehan1 @julianasopko @jackie-powers

**Comment by JacqSauer** [comment]
Burundi:
WHO reports 1,287 confirmed cases and 1,739 suspected cases (3,026 cases total)
ACDC reports 1,287 confirmed cases, 1,731 presumably discarded/negative cases, and 8 suspected cases (3,026 cases total)
Our line list reports 1,287 confirmed cases, 5 discarded/negative cases, and 1,739 suspected cases (3,031 cases total)

Options:
1. Need to remove some suspected cases (omit 5) to make the cumulative case total in our line list match 3,026 (JAS to do)
2. Can either switch most of our suspected cases to discarded/negative to match ACDC report
3. Or we can only report cumulative confirmed and cumulative suspected such as the WHO

@aimeehan1 @jackie-powers @julianasopko

**Comment by JacqSauer** [comment]
Cameroon:
WHO reports 6 confirmed cases and 93 suspected cases (98 total cases)
ACDC reports 6 confirmed cases, 76 presumably negative/discarded cases, and 27 suspected cases (109 total cases)
Our line list reports 6 confirmed cases and 97 suspected cases (103 total cases)

Options:
1. Make our cumulative case total match the cumulative ACDC case total (add 6 suspected or discarded/negative cases)
2. Only report suspected and confirmed cases
3. Report suspected, confirmed, and discarded cases following ACDC data

**Comment by JacqSauer** [comment]
Republic of the Congo:
The WHO reports 22 confirmed cases and 199 suspected cases (221 total cases)
ACDC reports 22 confirmed cases, 125 presumably negative cases, and 92 suspected cases (239 total cases)
Our line list reports 22 confirmed cases and 199 suspected cases (221 total cases)

**Comment by JacqSauer** [comment]
Gabon:
The WHO reports 2 confirmed cases and 13 suspected cases (15 total cases)
ACDC reports 2 confirmed cases and 22 presumably negative cases (24 total cases)
Our line list reports 2 confirmed cases, 9 discarded cases, and 13 suspected cases (24 total cases)

**Comment by aimeehan1** [comment]
@jackie-powers @JacqSauer @julianasopko 
Let's go country by country to review this list. We may need to make country-specific decisions and provide explanation as footnotes. 

Kenya --- we used official reports to discard (report negative cases).  https://health.go.ke/sites/default/files/2024-10/PRESS%20STATEMENT%20-%20MPOX%20%26%20MARBURG%20VIRUS%20UPDATE.pdf

Africa CDC also reports a 100% test rate for Kenya https://africacdc.org/download/africa-cdc-weekly-event-based-surveillance-report-october-2024/?ind=1728849665555&filename=Africa_CDC_Epidemic_Intelligence_Weekly_Report_12-October-2024.pdf&wpdmdl=18247&refresh=670fdc577d3861729092695

The most recent addition of 230 suspected cases is double counting (on 20241025). The discarded cases in our G.h database are the same cases that WHO reports as suspected. 

Most of the newly added suspected cases will be adjusted to omit_error with a footnote added to the briefing report (n=225). 5 of the suspected cases will be discarded so that our numbers align with WHO @244 total cases, including 14 confirmed. 

Moving forward, if we want to align with WHO counts, we could update the status for our discarded cases to suspected and make note that G.h suspected cases may include discarded. _Here is what the WHO dashboard website says about negative/discarded cases: " In some countries, suspected cases that undergo testing are not removed from the count, regardless of whether the test result is positive (confirmed case) or negative (discarded case). Moreover, not all countries have robust surveillance systems for mpox, meaning reported case counts are likely underestimate the extent of community transmission."_

**Comment by aimeehan1** [comment]
Liberia --- (same curation situation as Kenya), the most recent addition of 225 suspected cases is double counting (on 20241025). The discarded cases in our G.h database are the same cases that WHO reports as suspected.

However, Liberia, unlike Kenya, does not have a 100% test rate, so we will need to review and see how to best (re-)categorize the data.  The best option here may be to (re-)categorize G.h discarded cases as suspected?  we can't delineate exactly how many cases are suspected versus discarded without pulling data from multiple sources, making assumptions, plus this could create resource intensive calculations for one country and prone to error. So, we could flip and then align with WHO counts for suspected cases moving forward.

**Comment by aimeehan1** [comment]
Additional guidance from [WHO](https://cdn.who.int/media/docs/default-source/documents/emergencies/[mpox-sitrep_-41.pdf](https://cdn.who.int/media/docs/default-source/documents/emergencies/mpox-sitrep_-41.pdf?sfvrsn=a3758b8b_3&download=true)?sfvrsn=a3758b8b_3&download=true) to interpret their data. Supports our assumption that suspected counts, for most countries, include discarded and confirmed. 
![image](https://github.com/user-attachments/assets/834c60e0-85a2-4296-b4f3-bd0559e8975d)
